---

uid:
  host:       'nevendaar.com'
  site_id:    '4nevendaar'
  email:      'uid_email'
  password:   'uid_secret_password'
  user_agent: 'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:38.0) Gecko/20100101 Firefox/38.0'
